name: Build and deploy documentation book

on:
  push:
    branches:
      - master

jobs:
  book:
    name: Build and deploy book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install mdbook
        run: |
          (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
          (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.2" mdbook)
          cargo install-update -a

      - name: Build book
        run: |
          mdbook --version
          (cd docs && mv _theme theme && mdbook build)
          rustc ./docs/_installer/build-installer.rs
          ./build-installer

      - name: Deploy book
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
          token: ${{ secrets.GITHUB_TOKEN }}
          single-commit: true
